name: Build Windows Exe

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # Cho phép bạn bấm nút "Run" thủ công

jobs:
  build:
    runs-on: windows-latest # Build trên môi trường Windows
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        go mod tidy
        go build -o gh-preview.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gh-markdown-preview-windows
        path: gh-preview.exe

